### ISSUE TITLE
Wrong conversion between json and yaml

### ISSUE THREAD

**Issue by feserafim** [isa-group/ideas-json-module#3]
If you open a JSON file with the content:

``` json
{
  "id": "multiPlan",
  "docType": "TEMPLATE"
}
```

And then you convert it to YAML, you get **wrong** result:

``` javascript
{id: multiPlan, docType: TEMPLATE}
```

The expected result is:

``` yaml

---
  id: "multiPlan"
  docType: "TEMPLATE"

```
